### PR TITLE
Prepared for Composer usage & code style fixed

### PR DESCRIPTION
**Pull request by bertoost**
Hi Derrick,

With this PR all code has been moved to the root of the project. That's because I really would like to have this available via Composer, on www.packagist.org.
I have fixed the composer.json for it. If you create a free account, you can link it to your repository and you're done :-)

Also added a .gitattributes file where you can see things that have been ignored when someone downloads a zip or something from Github. Even a download via Composer will skip those files.
People don't have those files or folders in their project.

Code style is important for IDE's like phpStorm to recognize methods and variables. That's why I did that.

I didn't change more. Unless things that weren't used, I have removed that.

If you have any question, please feel free to ask.

Regards, Bert

### CODE REVIEW

**Comment by fb-derrick-grigg** [comment]
This looks pretty good and helpful. The one thing that can not be changed is the structure of having the 'migrationmanager' folder be a subfolder in the repo. I realize that does impact installations via composer but there are work arounds.

**Comment by bertoost** [comment]
Hi Derrick,
What is the reason the structure couldn't be changes? That isn’t clear to me. Maybe you can tell me so I can understand :-)

**Comment by fb-derrick-grigg** [comment]
I prefer to keep the non plugin specific files (ie screen shots, examples, license) outside the plugin directory. Also by keeping the plugin directory one in, I can make a more descriptive repo name.

**Comment by bertoost** [comment]
hi Derrick,
I understand what you're saying. But please download the zip-file from my fork repository, check the contents of the zipfile. It always contains a directory with the name of the repository and the branche name. And thanks to the added .gitattributes you can keep a download clean. So people using it, will not have files which they don't use.

Check;
image

I think this way it's even faster for people. They just have to extract the zipfile to craft/plugins/ directory and just rename it to "migrationmanager". They are not left with contents they don't need.
And then you can support Composer (even for Craft v2). Many of us do work with Composer and integration servers (as Jenkins) can handle this too.

I know it not keeps your root of the repository clean, but it comes with so many advantages. And per Craf v3 you can use any subfolder without having this issue, but for time being for v2....

Regards, Bert

**Comment by bertoost** [comment]
Updated with UI improvements. See screenshot;

image

Running migrations etc. still works of course :)

**Pull request merged**
